### ISSUE TITLE
norncage.s16

### ISSUE THREAD

**Issue by GonzoBurger** [Freylaverse/creatures#1]
This is my first time doing anything on github so sorry if I'm doing it wrong!

I was excited to try it, especially relocate as it's something I've been wanting to do but when pressing the button an error pops up saying norncage.s16 is missing.
![image](https://github.com/Freylaverse/creatures/assets/175026697/608dfe86-9cb7-44d1-9fcc-3c413992ab20)

I believe I got everything from github so I believe it is missing.

Thank you.

**Comment by Freylaverse** [comment]
Oh man, I could've sworn I'd put that in there! Should be fixed!
